In [1]:
import numpy as np

In [4]:
a = np.arange(1,10).reshape(3,3)

In [5]:
np.linalg.det(a)

-9.51619735392994e-16

In [6]:
b = a.T

In [7]:
b

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [8]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
np.dot(a,b)

array([[ 14,  32,  50],
       [ 32,  77, 122],
       [ 50, 122, 194]])

In [10]:
a = np.array([1,1,0], dtype = bool)
b = np.array([1,0,1], dtype = bool)

In [11]:
np.logical_or(a,b)

array([ True,  True,  True])

In [12]:
np.logical_and(a,b)

array([ True, False, False])

In [13]:
a = np.array([[1,2],[3,4]])

In [14]:
a

array([[1, 2],
       [3, 4]])

In [15]:
a.sum()

10

In [16]:
a.sum(axis=0)

array([4, 6])

In [17]:
a.sum(axis=1)

array([3, 7])

In [18]:
a.max()

4

In [19]:
a.shape()

TypeError: 'tuple' object is not callable

In [20]:
a.shape

(2, 2)