In [1]:
import numpy as np

In [2]:
x = np.matrix([[1,2,3,4],[5,6,7,8],[2,3,4,5],[6,7,8,9]])

In [3]:
x

matrix([[1, 2, 3, 4],
        [5, 6, 7, 8],
        [2, 3, 4, 5],
        [6, 7, 8, 9]])

In [4]:
x.shape

(4, 4)

In [5]:
a = np.matrix([[1,4,5],[1,2,3]])

In [6]:
b = np.matrix([[2,4],[5,6],[8,3]])

In [7]:
np.multiply(a,5)

matrix([[ 5, 20, 25],
        [ 5, 10, 15]])

In [8]:
a*b

matrix([[62, 43],
        [36, 25]])

In [9]:
np.transpose(a)

matrix([[1, 1],
        [4, 2],
        [5, 3]])

In [11]:
from numpy import linalg as LA

In [20]:
x = np.matrix([[1,3,4],[2,2,4],[3,5,8]])

In [21]:
x

matrix([[1, 3, 4],
        [2, 2, 4],
        [3, 5, 8]])

In [22]:
x.shape

(3, 3)

In [23]:
LA.matrix_rank(x)

2