In [1]:
import numpy as np

In [3]:
Z = np.zeros(10)
print(Z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [5]:
Z[4] = 1
print(Z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [6]:
Z=np.arange(10,49)
print(Z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]


In [12]:
Z=np.arange(10,49)
A=Z[0:10]
print(A)

[10 11 12 13 14 15 16 17 18 19]


In [18]:
Z=np.arange(16,32).reshape(4,4)
print(Z)

[[16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]


In [19]:
nz=np.nonzero([1,2,0,0,7,0,8])
print(nz)

(array([0, 1, 4, 6]),)


In [20]:
type(nz)

tuple

In [22]:
print(nz[0])

[0 1 4 6]


In [23]:
type(nz[0])

numpy.ndarray

In [24]:
Z=np.eye(3)
print(Z)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [25]:
Z=np.random.random((3,3,3))
print(Z)

[[[0.20776262 0.90227545 0.64639525]
  [0.11749557 0.20304185 0.06600628]
  [0.51833957 0.38758009 0.53103274]]

 [[0.86467105 0.73103297 0.68673341]
  [0.58948913 0.98851012 0.80273956]
  [0.92899802 0.9034309  0.28125085]]

 [[0.08128785 0.50570241 0.28508272]
  [0.07377183 0.7595997  0.75798224]
  [0.75223639 0.13295058 0.61678077]]]


In [28]:
Z=np.random.random((10,10))
max=Z.max()
min=Z.min()
print("Maximum = ",max)
print("Minimum = ",min)

Maximum =  0.9944636821824636
Minimum =  0.0048829007595633245


In [32]:
Z=np.random.random(30)
m=Z.mean()
print("Mean = ",m)

Mean =  0.5460271600797666


In [74]:
Z=np.ones((10,10))
print(Z[:,:],"\n")
Z[1:-1,1:-1] = 0
print(Z[:,:])


[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]] 

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [81]:
Z = np.diag(1+np.arange(5),k=0)
print(Z)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


In [91]:
Z = np.zeros((8,8),dtype=int)
Z[1::2,::2] = 1
Z[::2,1::2] = 1
print(Z,"\n")


[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]] 



In [96]:
print(np.unravel_index(100,(6,7,8)))

(1, 5, 4)


In [97]:
color = np.dtype([("r", np.ubyte, 1),
("g", np.ubyte, 1),
("b", np.ubyte, 1),
("a", np.ubyte, 1)])

type(color)

numpy.dtype

In [99]:
print(color["r"])

uint8


In [102]:
Z = np.dot(np.ones((2,3),dtype=int), np.ones((3,2),dtype=int))
print(Z)

[[3 3]
 [3 3]]


In [103]:
Z = np.arange(11)
Z[(3 < Z) & (Z <= 8)] *= -1
print(Z)

[ 0  1  2  3 -4 -5 -6 -7 -8  9 10]


In [112]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))


10
10


In [111]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

10
10


In [113]:
Z = np.random.uniform(0,10,10)
print(Z)
print (Z - Z%1)
print (np.floor(Z))
print (np.ceil(Z)-1)
print (Z.astype(int))
print (np.trunc(Z))

[6.94905563 9.62378041 0.36115604 1.89795895 0.27201703 4.80056337
 2.47593719 3.68061522 0.92491383 5.54521001]
[6. 9. 0. 1. 0. 4. 2. 3. 0. 5.]
[6. 9. 0. 1. 0. 4. 2. 3. 0. 5.]
[6. 9. 0. 1. 0. 4. 2. 3. 0. 5.]
[6 9 0 1 0 4 2 3 0 5]
[6. 9. 0. 1. 0. 4. 2. 3. 0. 5.]


In [114]:
Z = np.zeros((5,5))
Z += np.arange(5)
print(Z)


[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


In [131]:
def generate():
    for x in range(10):
        cube_list =[]
        yield x
Z = np.fromiter(generate(),dtype=int,count=-1)
print(Z)

[0 1 2 3 4 5 6 7 8 9]


In [132]:
Z = np.linspace(0,1,12,endpoint=True)[1:-1]
print(Z)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


In [134]:
Z = np.random.random(10)
Z.sort()
print(Z)

[0.2998375  0.3163068  0.34450007 0.35493818 0.37119645 0.65586128
 0.71264061 0.97571297 0.98095935 0.99438857]


In [135]:
Z = np.arange(10)
np.add.reduce(Z)

45

In [140]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
print(A)
print(B)
equal = np.allclose(A,B)
print(equal)

[1 0 0 1 1]
[0 0 1 1 0]
False
